// Generated by https://quicktype.io

export interface ComunicacionSiniestro {
  comunicacion_id: number | null;
  id : number | null;
  siniestro_id:    number;
  mensaje:         string;
  url_archivo:     string;
  fecha_mesaje:    string;
  es_operador:     number;
}


export interface ComunicacionSiniestroPost extends Omit<ComunicacionSiniestro, 'comunicacion_id' | 'id'> {

}
