// Generated by https://quicktype.io

export interface Precio {
  precio_id:       number;
  servicio_id:     number;
  precio:          number;
  limite_inferior: number;
  limite_superior: number;
  pendiente:       number;
  intercepto:      number;
  tipo_ecuacion:   number;
}
