// Generated by https://quicktype.io

export interface Rol {
  rol_id:        number;
  rol_name:      string;
  rol_structure: string;
  status:        number;
}


export interface RolToPost extends Omit<Rol, 'rol_id'>{

}
