// Generated by https://quicktype.io

export interface Siniestro {
  siniestro_id:      number | null;
  id : number | null;
  tipo_siniestro:    number;
  beneficiario_id:   number;
  descripcion:       string;
  fecha_siniestro:   string;
  pais_ocurrencia:   string;
  ciudad_ocurrencia: string;
  url_archivo:       string;
}


// Generated by https://quicktype.io

export interface SiniestroPost extends Omit<Siniestro, 'siniestro_id' | 'id'> {
}


