// Generated by https://quicktype.io

export interface Venta {
  venta_id:        number | null;
  id : number |null;
  username:        string;
  office_id:      number;
  cliente_id:      number;
  tipo_venta:      number;
  forma_pago:      number;
  cantidad:        string;
  tipo_descuento:  string;
  descuento:       string;
  plus:            number;
  status:          number;
  fecha_venta:     string;
  precio:          string;
  total:           string;
  total_pago:      number;
  tipo_valor:      number;
  descuento_extra: number;
  servicio_id : string;
  client_secret : string;
  comision : number;
  // extras_total:    string;
}

export interface VentaToPost extends Omit<Venta , 'venta_id' | 'id' | 'fecha_venta' | 'total' | 'total_pago'  | 'tipo_valor' | 'descuento_extra' | 'precio' | 'client_secret' >{
  extras_id : string;
  fecha_salida : string;
  fecha_retorno : string;
  multiviajes: string;

}


export interface VentaResp extends Omit<Venta , 'client_secret'>{
  extras_total : string;
}

